# curl "http://localhost:4444/v1/hello?name=wuha"
GET http://localhost:4444/v1/hello?name=wuha

###

# curl "http://localhost:9999/v2/hello/haha"
GET http://localhost:4444/v2/hello/haha

###

POST http://localhost:4444/v2/login
Content-Type: application/x-www-form-urlencoded

username=wuha&password=123

###

GET http://localhost:4444/assets/file1.txt

###

GET http://localhost:4444

###

GET http://localhost:4444/students

###
